### ISSUE TITLE
[DEFECT] Refreshing the staff status during staff selection will make the staff occupied

### ISSUE THREAD

**Issue by chungfg** [COMP3122-2324-Project/Simpsyber#25] opened 2024-03-01 14:01 UTC
This issue happened when i tried to refresh the staff status after selecting my staff for the task. The selected staff becomes unaviliable after pressing the refreshing button. I would have to close the "Select Staff" tab and reopen it in order to make the staff aviliable again. This issue exists on "Select Staff" tab for every tasks within the game.

Video for demonstrating the defect:
https://github.com/COMP3122-2324-Project/Simpsyber/assets/82433114/9a49acf3-a774-4257-9643-eee42667adfb

**Comment by TomLi0421** [comment] 2024-03-02 00:28
Duplicate of #2

**Comment by chungfg** [comment] 2024-03-02 01:35
Thanks for the reminder. @TomLi0421

**Closed as not planned** 2024-03-02 08:05 UTC
